name: Alert parent repository
# Everytime whenever LABEL is set as  "test ready"  in Pull Request
on:
  pull_request:
    types: [ labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Dispatch to `Cypress-Github-Acceptor`
    if: github.event.label.name == 'test ready'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Debug
        run: |
          echo "GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH"
          cat $GITHUB_EVENT_PATH
        shell: bash
      - name: Get PR Number
        id: pr_number
        run: |
          PR_NUMBER=$(echo "$GITHUB_EVENT_PATH" | jq -r '.number')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        shell: bash
      - name: Execute curl
        id: execute_curl
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}
          GITHUB_TOKEN: ${{ secrets.CYPRESS_DISPATCH_GITHUB_TOKEN }}
        run: ./setup-dispatcher.sh