name: Alert parent repository, Sputnik Automation on push

# Everytime whenever LABEL is set as  "test ready"  in Pull Request
on:
  pull_request:
    types: [ labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Dispatch to `Sputnik-Test-Automation`
    if: github.event.label.name == 'test ready'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: initialize_curl
        run: ./setup/setup-dispatcher.sh
      - id: execute_curl
        env:
          GITHUB_TOKEN: ${{ secrets.CYPRESS_DISPATCH_GITHUB_TOKEN }}
        run: ./setup-dispatcher.sh
